import type { Locale } from "@/lib/i18n";
import type { CorpusSeoProfile } from "@/lib/seo/corpus-route-keywords";

export const windowsInstallationSeeds: Record<Locale, readonly string[]> = {
  en: [
    "iptv smarters pro windows usa",
    "install iptv windows",
    "iptv windows installation",
    "iptv smarters pro windows guide",
    "how to install iptv on windows pc",
    "iptv windows setup",
    "iptv windows download",
  ],
  ca: [
    "iptv smarters pro windows canada",
    "install iptv windows canada",
    "iptv windows installation",
    "iptv smarters pro windows guide",
    "how to install iptv on windows",
    "iptv windows setup canada",
    "iptv windows download",
  ],
  uk: [
    "iptv smarters pro windows uk",
    "install iptv windows uk",
    "iptv windows installation",
    "iptv smarters pro windows guide",
    "how to install iptv on windows",
    "iptv windows setup uk",
    "iptv windows download",
  ],
  es: [
    "iptv smarters pro windows",
    "instalar iptv windows",
    "instalación iptv windows",
    "guía iptv smarters pro windows",
    "cómo instalar iptv en windows",
    "configuración iptv windows",
    "descargar iptv windows",
  ],
  fr: [
    "iptv smarters pro windows",
    "installer iptv windows",
    "installation iptv windows",
    "guide iptv smarters pro windows",
    "comment installer iptv sur windows",
    "configuration iptv windows",
    "télécharger iptv windows",
  ],
};

export const iosInstallationSeeds: Record<Locale, readonly string[]> = {
  en: [
    "iptv ios usa",
    "iptv smarters pro ios",
    "install iptv iphone",
    "iptv ipad",
    "iptv apple tv usa",
    "ios iptv app",
    "iptv on iphone",
  ],
  ca: [
    "iptv ios canada",
    "iptv smarters pro ios",
    "install iptv iphone canada",
    "iptv ipad",
    "iptv apple tv canada",
    "ios iptv app canada",
    "iptv on iphone",
  ],
  uk: [
    "iptv ios uk",
    "iptv smarters pro ios",
    "install iptv iphone uk",
    "iptv ipad",
    "iptv apple tv uk",
    "ios iptv app uk",
    "iptv on iphone",
  ],
  es: [
    "iptv ios",
    "iptv smarters pro ios",
    "instalar iptv iphone",
    "iptv ipad",
    "iptv apple tv",
    "app iptv ios",
    "iptv en iphone",
  ],
  fr: [
    "iptv ios",
    "iptv smarters pro ios",
    "installer iptv iphone",
    "iptv ipad",
    "iptv apple tv",
    "application iptv ios",
    "iptv sur iphone",
  ],
};

export const firestickInstallationSeeds: Record<Locale, readonly string[]> = {
  en: [
    "iptv firestick usa",
    "iptv smarters pro firestick",
    "install iptv firestick",
    "fire tv stick iptv",
    "amazon fire stick iptv usa",
    "iptv on firestick",
    "firestick iptv setup",
  ],
  ca: [
    "iptv firestick canada",
    "iptv smarters pro firestick canada",
    "install iptv firestick canada",
    "fire tv stick iptv canada",
    "amazon fire stick iptv",
    "iptv on firestick",
    "firestick iptv setup canada",
  ],
  uk: [
    "iptv firestick uk",
    "iptv smarters pro firestick uk",
    "install iptv firestick uk",
    "fire tv stick iptv uk",
    "amazon fire stick iptv",
    "iptv on firestick",
    "firestick iptv setup uk",
  ],
  es: [
    "iptv firestick",
    "iptv smarters pro firestick",
    "instalar iptv firestick",
    "fire tv stick iptv",
    "amazon fire stick iptv",
    "iptv en firestick",
    "configurar iptv firestick",
  ],
  fr: [
    "iptv firestick",
    "iptv smarters pro firestick",
    "installer iptv firestick",
    "fire tv stick iptv",
    "amazon fire stick iptv",
    "iptv sur firestick",
    "configuration iptv firestick",
  ],
};

export const smartTvInstallationSeeds: Record<Locale, readonly string[]> = {
  en: [
    "iptv smarters pro smart tv",
    "install iptv smart tv usa",
    "iptv smart tv setup",
    "iptv on samsung smart tv",
    "iptv on lg smart tv",
    "smart tv iptv app",
    "iptv smarters smart tv guide",
  ],
  ca: [
    "iptv smarters pro smart tv canada",
    "install iptv smart tv canada",
    "iptv smart tv setup canada",
    "iptv on samsung smart tv canada",
    "iptv on lg smart tv canada",
    "smart tv iptv app canada",
    "iptv smarters smart tv guide",
  ],
  uk: [
    "iptv smarters pro smart tv uk",
    "install iptv smart tv uk",
    "iptv smart tv setup uk",
    "iptv on samsung smart tv uk",
    "iptv on lg smart tv uk",
    "smart tv iptv app uk",
    "iptv smarters smart tv guide",
  ],
  es: [
    "iptv smarters pro smart tv",
    "instalar iptv smart tv",
    "configurar iptv smart tv",
    "iptv en smart tv samsung",
    "iptv en smart tv lg",
    "app iptv smart tv",
    "guía iptv smarters smart tv",
  ],
  fr: [
    "iptv smarters pro smart tv",
    "installer iptv smart tv",
    "configuration iptv smart tv",
    "iptv sur smart tv samsung",
    "iptv sur smart tv lg",
    "application iptv smart tv",
    "guide iptv smarters smart tv",
  ],
};

export const installationGuideSeeds: Record<Locale, readonly string[]> = {
  en: [
    "iptv installation guide usa",
    "how to install iptv",
    "iptv smarters pro installation",
    "iptv installation windows",
    "iptv installation android",
    "iptv installation ios",
    "iptv installation smart tv",
    "iptv installation firestick",
    "iptv setup guide",
    "iptv installation tutorial",
    "install iptv smarters pro",
    "iptv installation steps",
    "iptv installation instructions",
    "iptv installation help",
    "iptv installation support",
  ],
  ca: [
    "iptv installation guide canada",
    "how to install iptv canada",
    "iptv smarters pro installation canada",
    "iptv installation windows canada",
    "iptv installation android",
    "iptv installation ios canada",
    "iptv installation smart tv canada",
    "iptv installation firestick canada",
    "iptv setup guide canada",
    "iptv installation tutorial",
    "install iptv smarters pro canada",
    "iptv installation steps",
    "iptv installation instructions",
    "iptv installation help",
    "iptv installation support canada",
  ],
  uk: [
    "iptv installation guide uk",
    "how to install iptv uk",
    "iptv smarters pro installation uk",
    "iptv installation windows uk",
    "iptv installation android",
    "iptv installation ios uk",
    "iptv installation smart tv uk",
    "iptv installation firestick uk",
    "iptv setup guide uk",
    "iptv installation tutorial",
    "install iptv smarters pro uk",
    "iptv installation steps",
    "iptv installation instructions",
    "iptv installation help",
    "iptv installation support uk",
  ],
  es: [
    "guía instalación iptv",
    "cómo instalar iptv",
    "instalación iptv smarters pro",
    "instalación iptv windows",
    "instalación iptv android",
    "instalación iptv ios",
    "instalación iptv smart tv",
    "instalación iptv firestick",
    "guía configuración iptv",
    "tutorial instalación iptv",
    "instalar iptv smarters pro",
    "pasos instalación iptv",
    "instrucciones instalación iptv",
    "ayuda instalación iptv",
    "soporte instalación iptv",
  ],
  fr: [
    "guide installation iptv",
    "comment installer iptv",
    "installation iptv smarters pro",
    "installation iptv windows",
    "installation iptv android",
    "installation iptv ios",
    "installation iptv smart tv",
    "installation iptv firestick",
    "guide configuration iptv",
    "tutoriel installation iptv",
    "installer iptv smarters pro",
    "étapes installation iptv",
    "instructions installation iptv",
    "aide installation iptv",
    "support installation iptv",
  ],
};

export const resellerSeeds: Record<Locale, readonly string[]> = {
  en: [
    "iptv reseller program usa",
    "become iptv reseller",
    "iptv reseller",
    "white label iptv",
    "iptv reseller panel",
    "iptv business usa",
    "start iptv business",
    "iptv reseller account",
    "iptv reseller pricing usd",
    "iptv reseller support",
    "iptv reseller platform",
    "iptv reseller credits",
    "iptv reseller program benefits",
    "iptv reseller opportunity",
    "iptv reseller white label",
  ],
  ca: [
    "iptv reseller program canada",
    "become iptv reseller canada",
    "iptv reseller canada",
    "white label iptv canada",
    "iptv reseller panel",
    "iptv business canada",
    "start iptv business canada",
    "iptv reseller account",
    "iptv reseller pricing cad",
    "iptv reseller support",
    "iptv reseller platform",
    "iptv reseller credits",
    "iptv reseller program benefits",
    "iptv reseller opportunity canada",
    "iptv reseller white label",
  ],
  uk: [
    "iptv reseller program uk",
    "become iptv reseller uk",
    "iptv reseller uk",
    "white label iptv uk",
    "iptv reseller panel",
    "iptv business uk",
    "start iptv business uk",
    "iptv reseller account",
    "iptv reseller pricing GBP",
    "iptv reseller support",
    "iptv reseller platform",
    "iptv reseller credits",
    "iptv reseller program benefits",
    "iptv reseller opportunity uk",
    "iptv reseller white label",
  ],
  es: [
    "programa revendedor iptv",
    "convertirse revendedor iptv",
    "revendedor iptv",
    "iptv white label",
    "panel revendedor iptv",
    "negocio iptv",
    "iniciar negocio iptv",
    "cuenta revendedor iptv",
    "precios revendedor iptv",
    "soporte revendedor iptv",
    "plataforma revendedor iptv",
    "créditos revendedor iptv",
    "beneficios programa revendedor iptv",
    "oportunidad revendedor iptv",
    "revendedor iptv white label",
  ],
  fr: [
    "programme revendeur iptv",
    "devenir revendeur iptv",
    "revendeur iptv",
    "iptv white label",
    "panneau revendeur iptv",
    "business iptv",
    "démarrer business iptv",
    "compte revendeur iptv",
    "tarifs revendeur iptv",
    "support revendeur iptv",
    "plateforme revendeur iptv",
    "crédits revendeur iptv",
    "avantages programme revendeur iptv",
    "opportunité revendeur iptv",
    "revendeur iptv white label",
  ],
};

export const legalPrivacySeeds: Record<Locale, readonly string[]> = {
  en: [
    "IPTV privacy policy",
    "privacy policy IPTV",
    "IPTV data protection",
    "personal data IPTV",
    "StreamPro privacy policy",
    "IPTV Smarters Pro privacy",
  ],
  ca: [
    "IPTV privacy policy",
    "privacy policy IPTV",
    "IPTV data protection",
    "personal data IPTV",
    "StreamPro privacy policy",
    "IPTV Smarters Pro privacy",
  ],
  uk: [
    "IPTV privacy policy",
    "privacy policy IPTV",
    "IPTV data protection",
    "personal data IPTV",
    "StreamPro privacy policy",
    "IPTV Smarters Pro privacy",
  ],
  es: [
    "política de privacidad iptv",
    "privacidad iptv",
    "protección de datos iptv",
    "datos personales iptv",
    "política de privacidad StreamPro",
    "privacidad IPTV Smarters Pro",
  ],
  fr: [
    "politique de confidentialité iptv",
    "confidentialité iptv",
    "protection des données iptv",
    "données personnelles iptv",
    "politique de confidentialité StreamPro",
    "confidentialité IPTV Smarters Pro",
  ],
};

export const legalRefundSeeds: Record<Locale, readonly string[]> = {
  en: [
    "IPTV refund policy",
    "StreamPro refund",
    "IPTV subscription refund",
    "money back IPTV",
  ],
  ca: [
    "IPTV refund policy",
    "StreamPro refund",
    "IPTV subscription refund",
    "money back IPTV",
  ],
  uk: [
    "IPTV refund policy",
    "StreamPro refund",
    "IPTV subscription refund",
    "money back IPTV",
  ],
  es: [
    "política de reembolso iptv",
    "reembolso StreamPro",
    "reembolso suscripción iptv",
    "devolución iptv",
  ],
  fr: [
    "politique de remboursement iptv",
    "remboursement StreamPro",
    "remboursement abonnement iptv",
    "argent remboursé iptv",
  ],
};

export const legalTermsSeeds: Record<Locale, readonly string[]> = {
  en: [
    "IPTV terms of service",
    "StreamPro terms",
    "IPTV user agreement",
    "IPTV Smarters Pro terms",
  ],
  ca: [
    "IPTV terms of service Canada",
    "StreamPro terms Canada",
    "IPTV Canada user agreement",
    "IPTV Smarters Pro terms Canada",
    "CAD IPTV subscription terms",
  ],
  uk: [
    "IPTV terms of service uk",
    "StreamPro terms uk",
    "IPTV uk user agreement",
    "IPTV Smarters Pro terms uk",
    "GBP IPTV subscription terms",
  ],
  es: [
    "términos de servicio iptv",
    "términos StreamPro",
    "acuerdo de usuario iptv",
    "términos IPTV Smarters Pro",
  ],
  fr: [
    "conditions d'utilisation iptv",
    "conditions StreamPro",
    "contrat utilisateur iptv",
    "conditions IPTV Smarters Pro",
  ],
};

/** Localized slug pages: map English slug → corpus profile + seed lines */
export const blogListingSeeds: Record<Locale, readonly string[]> = {
  en: [
    "IPTV blog USA",
    "IPTV Smarters Pro news",
    "IPTV streaming tips",
    "IPTV setup articles",
    "live TV streaming guides",
    "IPTV tutorials",
  ],
  ca: [
    "IPTV blog Canada",
    "IPTV Smarters Pro Canada",
    "IPTV streaming tips Canada",
    "IPTV setup articles Canada",
    "live TV streaming guides Canada",
    "IPTV tutorials Canada",
  ],
  uk: [
    "IPTV blog uk",
    "IPTV Smarters Pro uk",
    "IPTV streaming tips uk",
    "IPTV setup articles uk",
    "live TV streaming guides uk",
    "IPTV tutorials uk",
  ],
  es: [
    "blog IPTV",
    "noticias IPTV Smarters Pro",
    "consejos streaming IPTV",
    "artículos configuración IPTV",
    "guías TV en vivo",
    "tutoriales IPTV",
  ],
  fr: [
    "blog IPTV",
    "actualités IPTV Smarters Pro",
    "conseils streaming IPTV",
    "articles configuration IPTV",
    "guides TV en direct",
    "tutoriels IPTV",
  ],
};

export const localizedSlugSeoConfig: Record<
  string,
  { profile: CorpusSeoProfile; seeds: Record<Locale, readonly string[]> }
> = {
  "iptv-installation-guide": { profile: "guide", seeds: installationGuideSeeds },
  "iptv-installation-windows": { profile: "windows", seeds: windowsInstallationSeeds },
  "iptv-installation-ios": { profile: "ios", seeds: iosInstallationSeeds },
  "iptv-installation-smart-tv": { profile: "smartTv", seeds: smartTvInstallationSeeds },
  "iptv-installation-firestick": { profile: "firestick", seeds: firestickInstallationSeeds },
  "iptv-reseller-program": { profile: "reseller", seeds: resellerSeeds },
  "privacy-policy": { profile: "legal", seeds: legalPrivacySeeds },
  "refund-policy": { profile: "legal", seeds: legalRefundSeeds },
  "terms-of-service": { profile: "legal", seeds: legalTermsSeeds },
};
