import type { Locale } from "@/lib/i18n";
import keywordCorpus from "@/data/seo/keyword-corpus.json";

/** Hand-curated homepage meta keywords (kept separate from generated corpus). */
export const CORE_SITE_KEYWORDS: Record<Locale, readonly string[]> = {
  en: [
    "iptv smarters pro subscription",
    "iptv subscription",
    "subscription iptv",
    "iptv smarters",
    "best iptv service",
    "IPTV",
    "IPTV service",
    "IPTV streaming",
    "premium IPTV",
    "IPTV provider",
    "best IPTV",
    "IPTV subscription service",
    "IPTV subscription provider",
    "IPTV subscription plans",
    "IPTV subscription price",
    "IPTV subscription cost",
    "IPTV Smarters Pro",
    "IPTV Smarters Pro subscription",
    "IPTV Smarters Pro service",
    "IPTV Smarters Pro codes",
    "IPTV Smarters Pro account",
    "IPTV Smarters Pro login",
    "IPTV Smarters Pro app",
    "IPTV Smarters Pro download",
    "IPTV Smarters Pro Windows",
    "IPTV Smarters Pro Android",
    "IPTV Smarters Pro iOS",
    "IPTV Smarters Pro Mac",
    "IPTV Smarters Pro APK",
    "streaming service",
    "live TV streaming",
    "4K IPTV",
    "HD IPTV",
    "FHD IPTV",
    "IPTV 4K streaming",
    "IPTV HD quality",
    "IPTV free test",
    "IPTV trial",
    "free IPTV test",
    "live TV channels",
    "VOD streaming",
    "video on demand",
    "IPTV channels",
    "IPTV movies",
    "IPTV series",
    "sports IPTV",
    "IPTV sports channels",
    "IPTV for Smart TV",
    "IPTV for Android",
    "IPTV for iOS",
    "IPTV for Windows",
    "IPTV for Mac",
    "IPTV for Firestick",
    "IPTV for Roku",
    "IPTV for Apple TV",
    "IPTV for MAG",
    "IPTV for Enigma",
    "M3U playlist",
    "Xtream Codes",
    "IPTV codes",
    "IPTV credentials",
    "IPTV account",
    "IPTV server",
    "IPTV reseller",
    "IPTV panel",
    "IPTV with EPG",
    "IPTV catch up",
    "IPTV recording",
    "IPTV multi-screen",
    "IPTV multi-device",
    "IPTV family plan",
    "IPTV USA",
    "best IPTV USA",
    "IPTV United States",
    "IPTV subscription USA",
    "IPTV service USA",
    "premium IPTV USA",
    "IPTV provider USA",
    "IPTV Smarters Pro USA",
    "American IPTV",
    "IPTV for Americans",
    "US IPTV service",
    "USA IPTV subscription",
    "IPTV plans USA",
    "IPTV pricing USD",
    "USD IPTV subscription",
    "IPTV dollars",
    "IPTV English USA",
    "IPTV for US residents",
    "IPTV Firestick USA",
    "IPTV Smart TV USA",
    "IPTV Android USA",
    "IPTV iOS USA",
    "IPTV Roku USA",
    "IPTV Apple TV USA",
    "live TV USA IPTV",
    "sports IPTV USA",
    "NFL IPTV streaming",
    "NBA IPTV streaming",
    "MLB IPTV streaming",
    "NHL IPTV streaming",
    "UFC PPV IPTV USA",
    "IPTV New York",
    "IPTV Los Angeles",
    "IPTV Chicago",
    "IPTV Houston",
    "IPTV Miami",
    "IPTV Dallas",
    "IPTV Atlanta",
    "IPTV Phoenix",
    "IPTV Philadelphia",
    "IPTV San Francisco",
    "IPTV Seattle",
    "IPTV Boston",
    "IPTV Denver",
    "IPTV Las Vegas",
    "IPTV Austin",
    "IPTV San Diego",
    "IPTV Detroit",
    "IPTV Orlando",
    "IPTV Tampa",
    "IPTV Charlotte",
    "IPTV Nashville",
    "IPTV Portland",
    "IPTV Minneapolis",
    "IPTV St Louis",
    "IPTV UK",
    "IPTV Canada",
    "IPTV worldwide",
    "international IPTV",
    "affordable IPTV",
    "cheap IPTV",
    "reliable IPTV",
    "stable IPTV",
    "IPTV without buffering",
    "IPTV anti-freeze",
    "IPTV 24/7 support",
    "instant IPTV activation",
    "IPTV setup guide",
    "how to use IPTV",
    "2026 FIFA World Cup",
    "FIFA World Cup 2026",
    "USA 2026 World Cup",
    "World Cup 2026 streaming",
    "watch World Cup on IPTV",
    "IPTV World Cup 2026",
    "soccer streaming IPTV",
    "football matches streaming",
    "World Cup live TV",
    "World Cup on Firestick",
    "World Cup on Smart TV",
    "IPTV Smarters Pro World Cup",
  ],
  ca: [
    "iptv canada",
    "iptv quebec",
    "iptv box",
    "iptv from canada",
    "best iptv",
    "iptv with box",
    "best canada iptv",
    "iptv for canada",
    "quebec iptv",
    "best iptv canada",
    "iptv subscription",
    "iptv smarters pro subscription",
    "subscription iptv",
    "iptv smarters",
    "best iptv service",
    "IPTV",
    "IPTV service",
    "IPTV streaming",
    "premium IPTV",
    "IPTV provider",
    "best IPTV",
    "IPTV subscription service",
    "IPTV subscription provider",
    "IPTV subscription plans",
    "IPTV subscription price",
    "IPTV subscription cost",
    "IPTV Smarters Pro",
    "IPTV Smarters Pro subscription",
    "IPTV Smarters Pro service",
    "IPTV Smarters Pro codes",
    "IPTV Smarters Pro account",
    "IPTV Smarters Pro login",
    "IPTV Smarters Pro app",
    "IPTV Smarters Pro download",
    "IPTV Smarters Pro Windows",
    "IPTV Smarters Pro Android",
    "IPTV Smarters Pro iOS",
    "IPTV Smarters Pro Mac",
    "IPTV Smarters Pro APK",
    "streaming service",
    "live TV streaming",
    "4K IPTV",
    "HD IPTV",
    "FHD IPTV",
    "IPTV 4K streaming",
    "IPTV HD quality",
    "IPTV free test",
    "IPTV trial",
    "free IPTV test",
    "live TV channels",
    "VOD streaming",
    "video on demand",
    "IPTV channels",
    "IPTV movies",
    "IPTV series",
    "sports IPTV",
    "IPTV sports channels",
    "IPTV for Smart TV",
    "IPTV for Android",
    "IPTV for iOS",
    "IPTV for Windows",
    "IPTV for Mac",
    "IPTV for Firestick",
    "IPTV for Roku",
    "IPTV for Apple TV",
    "IPTV for MAG",
    "IPTV for Enigma",
    "M3U playlist",
    "Xtream Codes",
    "IPTV codes",
    "IPTV credentials",
    "IPTV account",
    "IPTV server",
    "IPTV reseller",
    "IPTV panel",
    "IPTV with EPG",
    "IPTV catch up",
    "IPTV recording",
    "IPTV multi-screen",
    "IPTV multi-device",
    "IPTV family plan",
    "IPTV Canada",
    "IPTV Ontario",
    "IPTV British Columbia",
    "IPTV Alberta",
    "IPTV Manitoba",
    "IPTV CAD pricing",
    "IPTV subscription Canada CAD",
    "IPTV Toronto",
    "IPTV Montreal",
    "IPTV Vancouver",
    "IPTV Calgary",
    "IPTV Edmonton",
    "IPTV Ottawa",
    "IPTV Winnipeg",
    "IPTV Halifax",
    "IPTV worldwide",
    "international IPTV",
    "affordable IPTV",
    "cheap IPTV",
    "reliable IPTV",
    "stable IPTV",
    "IPTV without buffering",
    "IPTV anti-freeze",
    "IPTV 24/7 support",
    "instant IPTV activation",
    "IPTV setup guide",
    "how to use IPTV",
    "2026 FIFA World Cup",
    "FIFA World Cup 2026",
    "Canada 2026 World Cup",
    "World Cup 2026 streaming",
    "watch World Cup on IPTV",
    "IPTV World Cup 2026",
    "soccer streaming IPTV",
    "football matches streaming",
    "World Cup live TV",
    "World Cup on Firestick",
    "World Cup on Smart TV",
    "IPTV Smarters Pro World Cup",
  ],
  es: [
    "comprar iptv",
    "iptv españa",
    "iptv smarters pro",
    "iptv smarters",
    "suscripción iptv",
    "iptv españa comprar",
    "comprar códigos iptv smarters pro",
    "comprar codigo iptv smarters pro",
    "comprar codigo iptv",
    "IPTV",
    "servicio IPTV",
    "streaming IPTV",
    "IPTV premium",
    "proveedor IPTV",
    "mejor IPTV",
    "servicio de suscripción IPTV",
    "proveedor de suscripción IPTV",
    "planes de suscripción IPTV",
    "precio suscripción IPTV",
    "costo suscripción IPTV",
    "IPTV Smarters Pro",
    "suscripción IPTV Smarters Pro",
    "servicio IPTV Smarters Pro",
    "códigos IPTV Smarters Pro",
    "cuenta IPTV Smarters Pro",
    "inicio de sesión IPTV Smarters Pro",
    "aplicación IPTV Smarters Pro",
    "descargar IPTV Smarters Pro",
    "IPTV Smarters Pro Windows",
    "IPTV Smarters Pro Android",
    "IPTV Smarters Pro iOS",
    "IPTV Smarters Pro Mac",
    "IPTV Smarters Pro APK",
    "servicio de streaming",
    "transmisión de TV en vivo",
    "IPTV 4K",
    "IPTV HD",
    "IPTV FHD",
    "streaming IPTV 4K",
    "calidad IPTV HD",
    "prueba IPTV gratuita",
    "prueba IPTV",
    "test IPTV gratis",
    "canales de TV en vivo",
    "streaming VOD",
    "video bajo demanda",
    "canales IPTV",
    "películas IPTV",
    "series IPTV",
    "IPTV deportes",
    "canales deportivos IPTV",
    "IPTV para Smart TV",
    "IPTV para Android",
    "IPTV para iOS",
    "IPTV para Windows",
    "IPTV para Mac",
    "IPTV para Firestick",
    "IPTV para Roku",
    "IPTV para Apple TV",
    "IPTV para MAG",
    "IPTV para Enigma",
    "lista de reproducción M3U",
    "códigos Xtream",
    "códigos IPTV",
    "credenciales IPTV",
    "cuenta IPTV",
    "servidor IPTV",
    "revendedor IPTV",
    "panel IPTV",
    "IPTV con EPG",
    "IPTV catch up",
    "IPTV grabación",
    "IPTV multi-pantalla",
    "IPTV multi-dispositivo",
    "plan familiar IPTV",
    "IPTV España",
    "IPTV México",
    "IPTV Argentina",
    "IPTV Colombia",
    "IPTV Chile",
    "IPTV Latinoamérica",
    "IPTV mundial",
    "IPTV internacional",
    "IPTV económico",
    "IPTV barato",
    "IPTV confiable",
    "IPTV estable",
    "IPTV sin cortes",
    "IPTV anti-congelación",
    "soporte IPTV 24/7",
    "activación instantánea IPTV",
    "guía configuración IPTV",
    "cómo usar IPTV",
    "mejor IPTV España",
    "IPTV España precio",
    "IPTV España comprar",
    "donde comprar IPTV",
    "comprar IPTV online",
    "comprar suscripción IPTV",
    "comprar cuenta IPTV",
    "comprar código IPTV",
    "vender IPTV",
    "revender IPTV",
    "Copa Mundial FIFA 2026",
    "Mundial 2026 USA",
    "streaming del Mundial 2026",
    "ver el Mundial por IPTV",
    "IPTV Mundial 2026",
    "ver partidos de fútbol en IPTV",
    "Mundial en Firestick",
    "Mundial en Smart TV",
    "IPTV Smarters Pro Mundial",
    "Copa del Mundo 2026",
    "Mundial de fútbol en vivo IPTV",
    "partidos de fútbol streaming",
  ],
  fr: [
    "abonnement iptv",
    "iptv abonnement",
    "abonnement ip tv",
    "iptv smarters pro",
    "iptv smarters pro windows",
    "iptv smarters pro android",
    "IPTV",
    "service IPTV",
    "streaming IPTV",
    "IPTV premium",
    "fournisseur IPTV",
    "meilleur IPTV",
    "service d'abonnement IPTV",
    "fournisseur d'abonnement IPTV",
    "plans d'abonnement IPTV",
    "prix abonnement IPTV",
    "coût abonnement IPTV",
    "IPTV Smarters Pro",
    "abonnement IPTV Smarters Pro",
    "service IPTV Smarters Pro",
    "codes IPTV Smarters Pro",
    "compte IPTV Smarters Pro",
    "connexion IPTV Smarters Pro",
    "application IPTV Smarters Pro",
    "télécharger IPTV Smarters Pro",
    "IPTV Smarters Pro Windows",
    "IPTV Smarters Pro Android",
    "IPTV Smarters Pro iOS",
    "IPTV Smarters Pro Mac",
    "IPTV Smarters Pro APK",
    "service de streaming",
    "diffusion TV en direct",
    "IPTV 4K",
    "IPTV HD",
    "IPTV FHD",
    "streaming IPTV 4K",
    "qualité IPTV HD",
    "essai IPTV gratuit",
    "essai IPTV",
    "test IPTV gratuit",
    "chaînes TV en direct",
    "streaming VOD",
    "vidéo à la demande",
    "chaînes IPTV",
    "films IPTV",
    "séries IPTV",
    "IPTV sport",
    "chaînes sport IPTV",
    "IPTV pour Smart TV",
    "IPTV pour Android",
    "IPTV pour iOS",
    "IPTV pour Windows",
    "IPTV pour Mac",
    "IPTV pour Firestick",
    "IPTV pour Roku",
    "IPTV pour Apple TV",
    "IPTV pour MAG",
    "IPTV pour Enigma",
    "liste de lecture M3U",
    "codes Xtream",
    "codes IPTV",
    "identifiants IPTV",
    "compte IPTV",
    "serveur IPTV",
    "revendeur IPTV",
    "panneau IPTV",
    "IPTV avec EPG",
    "IPTV catch up",
    "IPTV enregistrement",
    "IPTV multi-écran",
    "IPTV multi-appareil",
    "forfait familial IPTV",
    "IPTV France",
    "IPTV Belgique",
    "IPTV Suisse",
    "IPTV Canada",
    "IPTV Québec",
    "IPTV Afrique",
    "IPTV mondial",
    "IPTV international",
    "IPTV abordable",
    "IPTV pas cher",
    "IPTV fiable",
    "IPTV stable",
    "IPTV sans gel",
    "IPTV anti-gel",
    "support IPTV 24/7",
    "activation instantanée IPTV",
    "guide configuration IPTV",
    "comment utiliser IPTV",
    "meilleur IPTV France",
    "IPTV France prix",
    "IPTV France acheter",
    "où acheter IPTV",
    "acheter IPTV en ligne",
    "acheter abonnement IPTV",
    "acheter compte IPTV",
    "acheter code IPTV",
    "vendre IPTV",
    "revendre IPTV",
    "Coupe du Monde FIFA 2026",
    "Coupe du Monde 2026 USA",
    "streaming Coupe du Monde 2026",
    "regarder la Coupe du Monde en IPTV",
    "IPTV Coupe du Monde 2026",
    "streaming matchs de football",
    "voir les matchs en direct sur IPTV",
    "Coupe du Monde sur Fire TV Stick",
    "Coupe du Monde sur Smart TV",
    "IPTV Smarters Pro Coupe du Monde",
    "Coupe du Monde de football 2026",
    "football streaming IPTV",
  ],
};

const corpus = keywordCorpus as Record<Locale, string[]>;

/** Extra phrases merged into homepage meta from generated corpus (avoids multi-KB meta tags). */
const META_EXTRA_FROM_CORPUS = 72;
const META_EXTRA_CA_FROM_CORPUS = 180;

const US_CITY_HINTS = [
  "new york",
  "los angeles",
  "chicago",
  "houston",
  "phoenix",
  "philadelphia",
  "san antonio",
  "san diego",
  "dallas",
  "austin",
  "jacksonville",
  "san jose",
  "fort worth",
  "columbus",
  "charlotte",
  "san francisco",
  "indianapolis",
  "seattle",
  "denver",
  "boston",
  "detroit",
  "nashville",
  "portland",
  "las vegas",
  "miami",
  "atlanta",
  "orlando",
  "tampa",
  "minneapolis",
  "st louis",
  "kansas city",
  "sacramento",
  "raleigh",
  "virginia beach",
  "oakland",
  "tucson",
  "albuquerque",
  "fresno",
  "long beach",
  "omaha",
  "cleveland",
  "pittsburgh",
  "cincinnati",
  "buffalo",
  "richmond",
  "hartford",
];

function isUsaFocusedKeyword(phrase: string): boolean {
  const p = phrase.toLowerCase();
  return (
    p.includes("united states") ||
    p.includes(" u.s.") ||
    p.includes(" usa") ||
    p.startsWith("usa ") ||
    p.includes("american") ||
    /\bus\b/.test(p) ||
    p.includes("usd") ||
    US_CITY_HINTS.some((city) => p.includes(city))
  );
}

function isCanadaFocusedKeyword(phrase: string): boolean {
  const p = phrase.toLowerCase();
  return (
    p.includes("canada") ||
    p.includes("quebec") ||
    p.includes("québec") ||
    p.includes("ontario") ||
    p.includes("toronto") ||
    p.includes("montreal") ||
    p.includes("montréal") ||
    p.includes("vancouver") ||
    p.includes("calgary") ||
    p.includes("edmonton") ||
    p.includes("ottawa") ||
    p.includes("winnipeg") ||
    p.includes("halifax") ||
    p.includes("cad") ||
    p.includes("british columbia") ||
    p.includes("alberta")
  );
}

function appendCorpusExtras(
  core: string[],
  seen: Set<string>,
  list: readonly string[],
  maxExtra: number,
  prefer?: (phrase: string) => boolean
): void {
  let added = 0;

  const tryAdd = (phrase: string) => {
    if (added >= maxExtra) return false;
    const n = phrase.toLowerCase().trim();
    if (!n || seen.has(n)) return false;
    seen.add(n);
    core.push(phrase);
    added += 1;
    return true;
  };

  if (prefer) {
    for (const phrase of list) {
      if (added >= maxExtra) break;
      if (!prefer(phrase)) continue;
      tryAdd(phrase);
    }
  }

  for (const phrase of list) {
    if (added >= maxExtra) break;
    tryAdd(phrase);
  }
}

/**
 * Keywords for homepage `<meta name="keywords">`: core list plus a deduped slice of the corpus.
 */
export function getHomepageKeywordList(locale: Locale): string[] {
  const core = [...CORE_SITE_KEYWORDS[locale]];
  const seen = new Set(core.map((k) => k.toLowerCase().trim()));
  const maxExtra = locale === "ca" ? META_EXTRA_CA_FROM_CORPUS : META_EXTRA_FROM_CORPUS;
  const list = corpus[locale] ?? [];
  const prefer =
    locale === "en"
      ? isUsaFocusedKeyword
      : locale === "ca"
        ? isCanadaFocusedKeyword
        : undefined;

  appendCorpusExtras(core, seen, list, maxExtra, prefer);
  return core;
}

/** Full generated vocabulary (2000 strings per locale). For tooling / future page-level mapping. */
export function getFullKeywordCorpus(locale: Locale): readonly string[] {
  return corpus[locale] ?? [];
}
