/** High-intent UK IPTV search phrases — homepage meta, hub cloud, and corpus seeding. */
export const UK_TRENDING_KEYWORDS = [
  "british iptv",
  "iptv uk",
  "best iptv uk",
  "iptv subscription uk",
  "iptv subscription",
  "iptv providers",
  "uk iptv provider",
  "iptv with subscription",
  "iptv smarters player",
  "iptv smarters pro uk",
  "iptv smarters uk",
  "united kingdom iptv",
  "iptv fire stick uk",
  "fire stick iptv uk",
  "amazon fire stick iptv uk",
  "iptv for firestick uk",
  "iptv free trial uk",
  "free iptv trial uk",
  "24 hour iptv trial uk",
  "cheapest iptv uk",
  "affordable iptv uk",
  "stable iptv uk",
  "reliable iptv uk",
  "iptv no buffering uk",
  "4k iptv uk",
  "hd iptv uk",
  "premier league iptv",
  "premier league iptv uk",
  "football iptv uk",
  "champions league iptv uk",
  "sports iptv uk",
  "live sports iptv uk",
  "mag box iptv uk",
  "formuler iptv uk",
  "android tv box iptv uk",
  "smart tv iptv uk",
  "samsung iptv uk",
  "lg iptv uk",
  "tivimate uk",
  "m3u playlist uk",
  "xtream codes uk",
  "iptv epg uk",
  "catch up tv iptv uk",
  "multi device iptv uk",
  "family iptv plan uk",
  "12 month iptv uk",
  "monthly iptv uk",
  "gbp iptv subscription",
  "iptv london",
  "iptv manchester",
  "iptv birmingham",
  "iptv liverpool",
  "iptv leeds",
  "iptv glasgow",
  "iptv edinburgh",
  "iptv belfast",
  "iptv scotland",
  "iptv wales",
  "iptv northern ireland",
  "iptv england",
  "iptv reseller uk",
  "wholesale iptv uk",
] as const;
