import type { Metadata, Viewport } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap", // Swap to custom font when loaded, but don't block
  preload: false, // Don't preload to reduce blocking
  adjustFontFallback: true, // Use fallback font immediately
  fallback: ["system-ui", "-apple-system", "sans-serif"],
  // Only load specific weights to reduce font file size
  weight: ["400", "600"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  display: "swap", // Swap to custom font when loaded
  preload: false,
  adjustFontFallback: true,
  fallback: ["system-ui", "-apple-system", "sans-serif"],
  // Only load specific weights
  weight: ["400", "600", "700"],
});

export async function generateMetadata(): Promise<Metadata> {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "https://www.pro-iptvsmarters.com";
  
  const title = "Best IPTV Subscription Service | IPTV Smarters Pro | 20,000+ Channels | Free Test";
  const description = "Get the #1 IPTV subscription service with IPTV Smarters Pro. Access 20,000+ live TV channels, movies, and series in 4K quality. 99.9% uptime guarantee. Free test available. Works on Windows, Android, iOS, Mac, Smart TV, Firestick. Instant activation.";
  const ogImage = `${baseUrl}/images/hero.png`;
  
  // Root metadata - default to English, but support all languages
  return {
    title,
    description,
    metadataBase: new URL(baseUrl),
    alternates: {
      canonical: `${baseUrl}/en/`, // Include trailing slash for consistency with next.config trailingSlash: true
      // Removed languages object - root page redirects, hreflang tags are handled by locale layout
    },
    openGraph: {
      type: "website",
      locale: "en_US",
      url: `${baseUrl}/en/`, // Include trailing slash for consistency
      siteName: "StreamPro - Premium IPTV Service",
      title,
      description,
      images: [
        {
          url: ogImage,
          width: 1200,
          height: 630,
          alt: title,
          type: "image/jpeg",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [ogImage],
      creator: "@streampro",
      site: "@streampro",
    },
    robots: {
      index: false, // Don't index root page - it redirects to /en/
      follow: true, // But follow links
      googleBot: {
        index: false, // Don't index root page
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    other: {
      "og:image:secure_url": ogImage,
      "og:image:type": "image/jpeg",
      "og:image:width": "1200",
      "og:image:height": "630",
      "og:image:alt": title,
    },
  };
}

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Preconnect to own domain for faster resource loading */}
        <link rel="preconnect" href={process.env.NEXT_PUBLIC_BASE_URL || "https://www.pro-iptvsmarters.com"} />
        {/* Preconnect to Google Fonts for faster font loading */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* DNS prefetch for external resources */}
        <link rel="dns-prefetch" href="https://fonts.googleapis.com" />
        <link rel="dns-prefetch" href="https://fonts.gstatic.com" />
        {/* Google Search Console verification */}
        <meta name="google-site-verification" content="UsDivhmxwn1peRYhvqO8TmyNGB180fGmIwM8BST2kh4" />
        {/* Hreflang tags are automatically generated by Next.js metadata API in locale layout */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var path = window.location.pathname;
                  var localeMatch = path.match(/^\/(en|es|fr)/);
                  if (localeMatch) {
                    document.documentElement.lang = localeMatch[1];
                  }
                } catch (e) {
                  // Suppress errors
                }
              })();
            `,
          }}
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  if (typeof window !== 'undefined' && window.addEventListener) {
                    window.addEventListener('error', function(e) {
                      try {
                        if (e && e.message && typeof e.message === 'string' && e.message.indexOf('ipapi.co') !== -1) {
                          e.preventDefault();
                        }
                      } catch (err) {
                        // Suppress
                      }
                    }, true);
                  }
                } catch (err) {
                  // Suppress
                }
              })();
            `,
          }}
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  if (typeof window !== 'undefined' && window.addEventListener) {
                    window.addEventListener('unhandledrejection', function(e) {
                      try {
                        if (e && e.reason) {
                          var reasonStr = '';
                          if (e.reason.message && typeof e.reason.message === 'string') {
                            reasonStr = e.reason.message;
                          } else {
                            try {
                              reasonStr = String(e.reason);
                            } catch (strErr) {
                              // Suppress
                            }
                          }
                          if (reasonStr.indexOf('ipapi.co') !== -1) {
                            e.preventDefault();
                          }
                        }
                      } catch (err) {
                        // Suppress
                      }
                    });
                  }
                } catch (err) {
                  // Suppress
                }
              })();
            `,
          }}
        />
        {/* Preload hero image only on desktop - on mobile, text is LCP */}
        <link rel="preload" as="image" href="/images/hero.png" fetchPriority="high" media="(min-width: 768px)" />
      </head>
      <body
        className={`${inter.variable} ${plusJakartaSans.variable} antialiased`}
      >
        <div id="root">
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
