import type { Metadata } from "next";
import { locales, type Locale } from "@/lib/i18n";
import { getHomepageMetadata } from "@/lib/utils/metadata-loader";

export async function buildLocaleHomepageMetadata(locale: Locale): Promise<Metadata> {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "https://www.pro-iptvsmarters.com";
  const locale = localeParam as Locale;
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "https://www.pro-iptvsmarters.com";
  const translations = getTranslations(locale);
  
  const localeMap: Record<Locale, string> = {
    en: "en_US",
    es: "es_ES",
    fr: "fr_FR",
  };

  // Load metadata from file
  const homepageMetadata = await getHomepageMetadata(locale);
  const title = homepageMetadata.title;
  const description = homepageMetadata.description;

  // Enhanced keywords for each language - Comprehensive SEO keywords
  const keywordsMap: Record<Locale, string[]> = {
    en: [
      // User requested keywords
      "iptv smarters pro subscription",
      "iptv subscription",
      "subscription iptv",
      "iptv smarters",
      "best iptv service",
      // Core IPTV keywords
      "IPTV",
      "IPTV service",
      "IPTV streaming",
      "premium IPTV",
      "IPTV provider",
      "best IPTV",
      "IPTV subscription service",
      "IPTV subscription provider",
      "IPTV subscription plans",
      "IPTV subscription price",
      "IPTV subscription cost",
      // IPTV Smarters Pro keywords
      "IPTV Smarters Pro",
      "IPTV Smarters Pro subscription",
      "IPTV Smarters Pro service",
      "IPTV Smarters Pro codes",
      "IPTV Smarters Pro account",
      "IPTV Smarters Pro login",
      "IPTV Smarters Pro app",
      "IPTV Smarters Pro download",
      "IPTV Smarters Pro Windows",
      "IPTV Smarters Pro Android",
      "IPTV Smarters Pro iOS",
      "IPTV Smarters Pro Mac",
      "IPTV Smarters Pro APK",
      // Streaming and quality keywords
      "streaming service",
      "live TV streaming",
      "4K IPTV",
      "HD IPTV",
      "FHD IPTV",
      "IPTV 4K streaming",
      "IPTV HD quality",
      "IPTV free test",
      "IPTV trial",
      "free IPTV test",
      // Content keywords
      "live TV channels",
      "VOD streaming",
      "video on demand",
      "IPTV channels",
      "IPTV movies",
      "IPTV series",
      "sports IPTV",
      "IPTV sports channels",
      // Device compatibility
      "IPTV for Smart TV",
      "IPTV for Android",
      "IPTV for iOS",
      "IPTV for Windows",
      "IPTV for Mac",
      "IPTV for Firestick",
      "IPTV for Roku",
      "IPTV for Apple TV",
      "IPTV for MAG",
      "IPTV for Enigma",
      // Technical keywords
      "M3U playlist",
      "Xtream Codes",
      "IPTV codes",
      "IPTV credentials",
      "IPTV account",
      "IPTV server",
      "IPTV reseller",
      "IPTV panel",
      // Service features
      "IPTV with EPG",
      "IPTV catch up",
      "IPTV recording",
      "IPTV multi-screen",
      "IPTV multi-device",
      "IPTV family plan",
      // Geographic keywords
      "IPTV USA",
      "IPTV UK",
      "IPTV Canada",
      "IPTV worldwide",
      "international IPTV",
      // Additional relevant keywords
      "affordable IPTV",
      "cheap IPTV",
      "reliable IPTV",
      "stable IPTV",
      "IPTV without buffering",
      "IPTV anti-freeze",
      "IPTV 24/7 support",
      "instant IPTV activation",
      "IPTV setup guide",
      "how to use IPTV",
      // World Cup 2026 (USA) SEO intent
      "2026 FIFA World Cup",
      "FIFA World Cup 2026",
      "USA 2026 World Cup",
      "World Cup 2026 streaming",
      "watch World Cup on IPTV",
      "IPTV World Cup 2026",
      "soccer streaming IPTV",
      "football matches streaming",
      "World Cup live TV",
      "World Cup on Firestick",
      "World Cup on Smart TV",
      "IPTV Smarters Pro World Cup",
    ],
    es: [
      // User requested keywords
      "comprar iptv",
      "iptv españa",
      "iptv smarters pro",
      "iptv smarters",
      "suscripción iptv",
      "iptv españa comprar",
      "comprar códigos iptv smarters pro",
      "comprar codigo iptv smarters pro",
      "comprar codigo iptv",
      // Core IPTV keywords
      "IPTV",
      "servicio IPTV",
      "streaming IPTV",
      "IPTV premium",
      "proveedor IPTV",
      "mejor IPTV",
      "servicio de suscripción IPTV",
      "proveedor de suscripción IPTV",
      "planes de suscripción IPTV",
      "precio suscripción IPTV",
      "costo suscripción IPTV",
      // IPTV Smarters Pro keywords
      "IPTV Smarters Pro",
      "suscripción IPTV Smarters Pro",
      "servicio IPTV Smarters Pro",
      "códigos IPTV Smarters Pro",
      "cuenta IPTV Smarters Pro",
      "inicio de sesión IPTV Smarters Pro",
      "aplicación IPTV Smarters Pro",
      "descargar IPTV Smarters Pro",
      "IPTV Smarters Pro Windows",
      "IPTV Smarters Pro Android",
      "IPTV Smarters Pro iOS",
      "IPTV Smarters Pro Mac",
      "IPTV Smarters Pro APK",
      // Streaming and quality keywords
      "servicio de streaming",
      "transmisión de TV en vivo",
      "IPTV 4K",
      "IPTV HD",
      "IPTV FHD",
      "streaming IPTV 4K",
      "calidad IPTV HD",
      "prueba IPTV gratuita",
      "prueba IPTV",
      "test IPTV gratis",
      // Content keywords
      "canales de TV en vivo",
      "streaming VOD",
      "video bajo demanda",
      "canales IPTV",
      "películas IPTV",
      "series IPTV",
      "IPTV deportes",
      "canales deportivos IPTV",
      // Device compatibility
      "IPTV para Smart TV",
      "IPTV para Android",
      "IPTV para iOS",
      "IPTV para Windows",
      "IPTV para Mac",
      "IPTV para Firestick",
      "IPTV para Roku",
      "IPTV para Apple TV",
      "IPTV para MAG",
      "IPTV para Enigma",
      // Technical keywords
      "lista de reproducción M3U",
      "códigos Xtream",
      "códigos IPTV",
      "credenciales IPTV",
      "cuenta IPTV",
      "servidor IPTV",
      "revendedor IPTV",
      "panel IPTV",
      // Service features
      "IPTV con EPG",
      "IPTV catch up",
      "IPTV grabación",
      "IPTV multi-pantalla",
      "IPTV multi-dispositivo",
      "plan familiar IPTV",
      // Geographic keywords
      "IPTV España",
      "IPTV México",
      "IPTV Argentina",
      "IPTV Colombia",
      "IPTV Chile",
      "IPTV Latinoamérica",
      "IPTV mundial",
      "IPTV internacional",
      // Additional relevant keywords
      "IPTV económico",
      "IPTV barato",
      "IPTV confiable",
      "IPTV estable",
      "IPTV sin cortes",
      "IPTV anti-congelación",
      "soporte IPTV 24/7",
      "activación instantánea IPTV",
      "guía configuración IPTV",
      "cómo usar IPTV",
      "mejor IPTV España",
      "IPTV España precio",
      "IPTV España comprar",
      "donde comprar IPTV",
      "comprar IPTV online",
      "comprar suscripción IPTV",
      "comprar cuenta IPTV",
      "comprar código IPTV",
      "vender IPTV",
      "revender IPTV",
      // World Cup 2026 (USA) SEO intent
      "Copa Mundial FIFA 2026",
      "Mundial 2026 USA",
      "streaming del Mundial 2026",
      "ver el Mundial por IPTV",
      "IPTV Mundial 2026",
      "ver partidos de fútbol en IPTV",
      "Mundial en Firestick",
      "Mundial en Smart TV",
      "IPTV Smarters Pro Mundial",
      "Copa del Mundo 2026",
      "Mundial de fútbol en vivo IPTV",
      "partidos de fútbol streaming",
    ],
    fr: [
      // User requested keywords
      "abonnement iptv",
      "iptv abonnement",
      "abonnement ip tv",
      "iptv smarters pro",
      "iptv smarters pro windows",
      "iptv smarters pro android",
      // Core IPTV keywords
      "IPTV",
      "service IPTV",
      "streaming IPTV",
      "IPTV premium",
      "fournisseur IPTV",
      "meilleur IPTV",
      "service d'abonnement IPTV",
      "fournisseur d'abonnement IPTV",
      "plans d'abonnement IPTV",
      "prix abonnement IPTV",
      "coût abonnement IPTV",
      // IPTV Smarters Pro keywords
      "IPTV Smarters Pro",
      "abonnement IPTV Smarters Pro",
      "service IPTV Smarters Pro",
      "codes IPTV Smarters Pro",
      "compte IPTV Smarters Pro",
      "connexion IPTV Smarters Pro",
      "application IPTV Smarters Pro",
      "télécharger IPTV Smarters Pro",
      "IPTV Smarters Pro Windows",
      "IPTV Smarters Pro Android",
      "IPTV Smarters Pro iOS",
      "IPTV Smarters Pro Mac",
      "IPTV Smarters Pro APK",
      // Streaming and quality keywords
      "service de streaming",
      "diffusion TV en direct",
      "IPTV 4K",
      "IPTV HD",
      "IPTV FHD",
      "streaming IPTV 4K",
      "qualité IPTV HD",
      "essai IPTV gratuit",
      "essai IPTV",
      "test IPTV gratuit",
      // Content keywords
      "chaînes TV en direct",
      "streaming VOD",
      "vidéo à la demande",
      "chaînes IPTV",
      "films IPTV",
      "séries IPTV",
      "IPTV sport",
      "chaînes sport IPTV",
      // Device compatibility
      "IPTV pour Smart TV",
      "IPTV pour Android",
      "IPTV pour iOS",
      "IPTV pour Windows",
      "IPTV pour Mac",
      "IPTV pour Firestick",
      "IPTV pour Roku",
      "IPTV pour Apple TV",
      "IPTV pour MAG",
      "IPTV pour Enigma",
      // Technical keywords
      "liste de lecture M3U",
      "codes Xtream",
      "codes IPTV",
      "identifiants IPTV",
      "compte IPTV",
      "serveur IPTV",
      "revendeur IPTV",
      "panneau IPTV",
      // Service features
      "IPTV avec EPG",
      "IPTV catch up",
      "IPTV enregistrement",
      "IPTV multi-écran",
      "IPTV multi-appareil",
      "forfait familial IPTV",
      // Geographic keywords
      "IPTV France",
      "IPTV Belgique",
      "IPTV Suisse",
      "IPTV Canada",
      "IPTV Québec",
      "IPTV Afrique",
      "IPTV mondial",
      "IPTV international",
      // Additional relevant keywords
      "IPTV abordable",
      "IPTV pas cher",
      "IPTV fiable",
      "IPTV stable",
      "IPTV sans gel",
      "IPTV anti-gel",
      "support IPTV 24/7",
      "activation instantanée IPTV",
      "guide configuration IPTV",
      "comment utiliser IPTV",
      "meilleur IPTV France",
      "IPTV France prix",
      "IPTV France acheter",
      "où acheter IPTV",
      "acheter IPTV en ligne",
      "acheter abonnement IPTV",
      "acheter compte IPTV",
      "acheter code IPTV",
      "vendre IPTV",
      "revendre IPTV",
      // World Cup 2026 (USA) SEO intent
      "Coupe du Monde FIFA 2026",
      "Coupe du Monde 2026 USA",
      "streaming Coupe du Monde 2026",
      "regarder la Coupe du Monde en IPTV",
      "IPTV Coupe du Monde 2026",
      "streaming matchs de football",
      "voir les matchs en direct sur IPTV",
      "Coupe du Monde sur Fire TV Stick",
      "Coupe du Monde sur Smart TV",
      "IPTV Smarters Pro Coupe du Monde",
      "Coupe du Monde de football 2026",
      "football streaming IPTV",
    ],
  };

  // Generate hreflang alternates
  const alternates: Record<string, string> = {};
  locales.forEach((loc) => {
    alternates[loc] = `${baseUrl}/${loc}/`;
  });
  // Add x-default pointing to English (default locale)
  alternates['x-default'] = `${baseUrl}/en/`;

  // Site name translations
  const siteNameMap: Record<Locale, string> = {
    en: "StreamPro - Premium IPTV Service",
    es: "StreamPro - Servicio IPTV Premium",
    fr: "StreamPro - Service IPTV Premium",
  };

  return {
    title,
    description,
    keywords: keywordsMap[locale],
    authors: [{ name: "StreamPro" }],
    creator: "StreamPro",
    publisher: "StreamPro",
    applicationName: "StreamPro IPTV",
    formatDetection: {
      email: false,
      address: false,
      telephone: false,
    },
    metadataBase: new URL(baseUrl),
    alternates: {
      canonical: `${baseUrl}/${locale}/`, // Include trailing slash to match next.config trailingSlash: true
      languages: alternates,
    },
    openGraph: {
      type: "website",
      locale: localeMap[locale],
      url: `${baseUrl}/${locale}/`, // Include trailing slash for consistency
      siteName: siteNameMap[locale],
      title,
      description,
      images: [
        {
          url: `${baseUrl}/images/hero.png`,
          width: 1200,
          height: 630,
          alt: title,
          type: "image/jpeg",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [`${baseUrl}/images/hero.png`],
      creator: "@streampro",
      site: "@streampro",
    },
    other: {
      "og:image:secure_url": `${baseUrl}/images/hero.png`,
      "og:image:type": "image/jpeg",
      "og:image:width": "1200",
      "og:image:height": "630",
      "og:image:alt": title,
      "article:author": "StreamPro",
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    verification: {
      // Add your verification codes here when available
      // google: "your-google-verification-code",
      // yandex: "your-yandex-verification-code",
      // bing: "your-bing-verification-code",
    },
  };
}
